language: node_js

node_js:
  - lts/*

script:
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main

notifications:
  webhooks:
    urls:
      - https://hooks.spike.sh/0e76c5e2468db67b46be/push-events
    on_success: never # default: always
    on_failure: always # default: always
    on_start:   never # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always