language: node_js

node_js:
  - lts/*

cache: yarn

script:
  - yarn run test
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
